### ISSUE TITLE
Failed to load the tree-view-bundler package

### ISSUE THREAD

**Issue by pluff** [shemerey/atom-tree-view-bundler#5]
Try to install your package.

**Atom Version**: 1.2.0
**System**: Mac OS X 10.10.5
**Thrown From**: [tree-view-bundler](https://github.com/shemerey/atom-tree-view-bundler) package, v0.0.2

### Stack Trace

Failed to load the tree-view-bundler package

```
At Cannot find module 'sleep'

Error: Cannot find module 'sleep'
    at Module._resolveFilename (module.js:336:15)
    at Function.Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/shutin/.atom/packages/tree-view-bundler/lib/tree-view-bundler-view.coffee:4:9)
    at Object.<anonymous> (/Users/shutin/.atom/packages/tree-view-bundler/lib/tree-view-bundler-view.coffee:1:1)
    at Module._compile (module.js:434:26)
    at Object.defineProperty.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:190:21)
    at Module.load (module.js:355:32)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "packagesWithKeymapsDisabled": [
      "ruby-test",
      "ruby-block"
    ],
    "disabledPackages": [
      "symbols-view",
      "package-cop"
    ],
    "projectHome": "/Users/shutin/www"
  }
}
```

### Installed Packages

```coffee
# User
atom-ctags, v4.4.0
autocomplete-ruby, v0.1.0
file-icons, v1.6.11
language-haml, v0.23.6
language-rspec, v0.3.0
linter, v1.10.0
linter-rubocop, v0.4.4
tree-view-bundler, v0.0.2

# Dev
No dev packages
```

**Comment by shemerey** [comment]
plz upgrade to `0.0.3`
